name: container-build-push
description: Simple github action that uses various docker actions to build and publish multiarch container images with meaningful tags.
inputs:
  context:
    description: "build's context is the set of files located in the specified path"
    default: "."
  file:
    description: "path to the Dockerfile (default ./Dockerfile)"
    default: "./Dockerfile"
  checkout-deploy-key:
    description: "checkout deploy key"
    default: ""
  registry:
    description: "container registry"
    default: ghcr.io
    required: true
  user:
    description: "container registry user"
    default: "${{ github.actor }}"
    required: true
  token:
    description: "container registry token"
    required: true
  platforms:
    description: "container target platforms"
    default: "linux/amd64,linux/arm/v7,linux/arm64"
runs:
  using: "composite"
  steps:
    - name: checkout with github token
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      if: ${{ inputs.checkout-deploy-key == '' }}

    - name: checkout with deploy key
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        ssh-key: "${{ inputs.checkout-deploy-key }}"
      if: ${{ inputs.checkout-deploy-key != '' }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

    - name: Log into registry ${{ inputs.registry }}
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.user }}
        password: ${{ inputs.token }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
      with:
        images: ${{ inputs.registry }}/${{ github.repository }}
        tags: |
          type=semver,pattern={{version}}
          type=edge,branch=main
          type=edge,branch=master
          type=ref,event=branch
          type=sha,prefix=,format=short

    - name: Build and push container image
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        push: true
        provenance: false # https://github.com/docker/build-push-action/issues/820
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: ${{ inputs.platforms }}
