name: container-build-push
description: Simple github action that uses various docker actions to build and publish multiarch container images with meaningful tags.
inputs:
  checkout-deploy-key:
    description: "checkout deploy key"
    default: ""
  registry:
    description: "container registry"
    default: ghcr.io
    required: true
  user:
    description: "container registry user"
    default: ${{ github.actor }}
    required: true
  token:
    description: "container registry token"
    required: true
  platforms:
    description: "container target platforms"
    default: "linux/amd64,linux/arm/v7,linux/arm64"
runs:
  using: "composite"
  steps:
    - name: checkout with github token
      uses: actions/checkout@v2
      if: ${{ inputs.checkout-deploy-key == '' }}

    - name: checkout with deploy key
      uses: actions/checkout@v2
      with:
        ssh-key: "${{ inputs.checkout-deploy-key }}"
      if: ${{ inputs.checkout-deploy-key != '' }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log into registry ${{ inputs.registry }}
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.user }}
        password: ${{ inputs.token }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ inputs.registry }}/${{ github.repository }}
        tags: |
          type=ref,event=branch
          type=sha,prefix=,format=short
          type=edge,branch=main
          type=edge,branch=master
          type=semver,pattern={{version}}

    - name: Build and push container image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: ${{ inputs.platforms }}
